# These are supported funding model platforms

github: [steierma] # Replace with your GitHub username if you use GitHub Sponsors
# patreon: your-patreon-username
# ko_fi: your-ko-fi-username
# buy_me_a_coffee: your-buy-me-a-coffee-username
# custom: ['https://paypal.me/your-paypal-link', 'https://your-custom-domain.com/donate']